apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          resources:
            requests:
              memory: '512Mi'
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value:
            - name: POSTGRES_USER
              value:
